CREATE TABLE T_STOCK_COMPARIAON (
	CODE                       CHAR(4) NOT NULL,
	TRADDAY                    DATE    NOT NULL,
	DAY_BEFORE_RATIO           FLOAT,
	DAY_BEFORE_RATIO_HISTORY   FLOAT,
	PRIMARY KEY(CODE,TRADDAY)
)
;