CREATE TABLE T_STOCK(
	APPLYDATE          CHAR(8)      NOT NULL,
	CODE               CHAR(4)      NOT NULL,
	NAME               VARCHAR(500) NOT NULL,
	MERKET_PROD_DIV    CHAR(3),
	INDUSTRY_CODE_33   CHAR(2),
	INDUSTRY_CODE_17   CHAR(2),
	SCALE_CODE         CHAR(1),
	PRIMARY KEY(APPLYDATE,CODE)
)