CREATE TABLE T_STOCK_QUOTE(
	CODE               CHAR(4) NOT NULL,
	TRADDAY            DATE    NOT NULL,
	OPEN_RATE          MEDIUMINT,
	HIGH_PRICE         MEDIUMINT,
	LOW_PRICE          MEDIUMINT,
	CLOSE_RATE         MEDIUMINT,
	TRADING_VOLUME     MEDIUMINT,
	CLOSE_ADJUST_VALUE FLOAT,
	PRIMARY KEY(CODE,TRADDAY)
);